---
- name: Set Servername
  ansible.builtin.set_fact:
    servername: "{{ inventory_hostname if hostname_use_fqdn | bool else inventory_hostname_short }}"

- name: Set hostname
  become: true
  ansible.builtin.hostname:
    name: "{{ servername }}"

- name: Copy /etc/hostname
  become: true
  ansible.builtin.template:
    src: config.j2
    dest: /etc/hostname
    owner: root
    group: root
    mode: 0644
